### ISSUE TITLE
[OpenLib/SuitsTerminal] issue and error log

### ISSUE THREAD

**Issue by CoolLKKPS** [darmuh/OpenLib#3]
first issue:
[Error  : Unity Log] ArgumentNullException: Value cannot be null.
Parameter name: key
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <787acc3c9a4c471ba7d971300105af24>:IL_0008)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
OpenLib.CoreMethods.LogicHandling.GetNewDisplayText (OpenLib.CoreMethods.MainListing providedListing, TerminalNode& node) (at ./CoreMethods/LogicHandling.cs:33)
OpenLib.Events.EventUsage.OnParseSent (TerminalNode& node) (at ./Events/EventUsage.cs:86)
OpenLib.Events.Events+TerminalNodeEvent.NodeInvoke (TerminalNode& original) (at ./Events/Events.cs:44)
OpenLib.Terminal_ParsePlayerSentence_Patch.Postfix (TerminalNode& __result) (at ./PatchThings/TerminalPatcher.cs:75)
(wrapper dynamic-method) Terminal.DMD<Terminal::ParsePlayerSentence>(Terminal)
Terminal.OnSubmit () (at <d491ed1d4cc34874a2498af41192fe04>:IL_0060)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_000E)
TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001B)
TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_00B0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_007C)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0000)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067)
UnityEngine.EventSystems.EventSystem:Update()

second: when using suitsterminal and more_suit mods, suits on suit rack will not look right when join as client
u might need to set `Make Suits Fit on Rack = false` in more_suit config

**Comment by CoolLKKPS** [comment]
@darmuh issue when updated to the newest version, pls test, not install `darmuhsTerminalStuff`

**Comment by CoolLKKPS** [comment]
Modpack Link if u want: https://1drv.ms/f/c/c26722dc35962b5c/ElwrljXcImcggMKLCgAAAAABXdwXiAVT3j3zNnyNZw3uXg

**Comment by darmuh** [comment]
> @darmuh issue when updated to the newest version, pls test, not install `darmuhsTerminalStuff`

I've got a similar report in the modding discord. Looking into it now, seems to be an issue with the event I modified for darmuhsTerminalStuff. When the event does not have anyone using it the node is returning null. Should have a fix ready for it soon

**Comment by darmuh** [comment]
> second: when using suitsterminal and more_suit mods, suits on suit rack will not look right when join as client u might need to set `Make Suits Fit on Rack = false` in more_suit config

For this issue can you make an issue on the [suitsTerminal github](https://github.com/darmuh/suitsTerminal)?

**Comment by darmuh** [comment]
first issue should be fixed in 0.2.7 now. Thanks for the report!
